// Generated by CoffeeScript 1.6.3
(function() {
  var firstNavItem, hideSub, itemContainer, items, showSub, subItemContainer, subItems;

  items = ["All Deals", "New Deals", "Food & Drink", "Events & Activities", "Beauty & Spas", "Health & Fitness", "Home & Garden", "Automotive", "Shopping"];

  firstNavItem = null;

  itemContainer = new View({
    width: 640,
    clip: false
  });

  items.map(function(item, index) {
    var itemView;
    itemView = new View({
      superView: itemContainer,
      width: 640,
      height: 88,
      x: 0,
      y: 1000 + index * 88,
      opacity: 0,
      clip: false,
      "class": 'framer list'
    });
    if (index === 0) {
      firstNavItem = itemView;
    }
    itemView.style = {
      borderBottom: "1px solid rgba(0,0,0,.2)",
      lineHeight: "" + itemView.height + "px",
      paddingLeft: "20px",
      cursor: "pointer",
      backgroundColor: "#f0f0f0"
    };
    if (index > 1) {
      itemView.html = "" + item + " <span></span>";
    } else {
      itemView.html = "" + item;
    }
    utils.delay(index * 30, function() {
      return itemView.animate({
        properties: {
          y: 216 + index * 88,
          opacity: 1
        },
        curve: "spring(500,30,800)"
      });
    });
    return itemView.on(Events.TouchStart, function() {
      var moveTop, originalPosition;
      if (index > 0 && itemView.y !== 216) {
        originalPosition = itemView.y;
        moveTop = new Animation({
          view: itemView,
          properties: {
            y: 216
          },
          curve: "ease-out",
          time: 300
        });
        itemView.html = "" + item + " <span class='close'></span>";
        moveTop.start();
        utils.delay(100, showSub);
        return itemView.on(Events.TouchStart, function(event) {
          var moveBack;
          itemView.html = "" + item + " <span></span>";
          moveBack = new Animation({
            view: itemView,
            properties: {
              y: originalPosition
            },
            curve: "ease-out",
            time: 300
          });
          moveBack.start();
          return hideSub();
        });
      }
    });
  });

  subItems = ["Sub Cat One (32)", "Sub Cat Two (14)", "Sub Cat Three (21)", "Sub Cat Four (11)", "Sub Cat Five (23)", "Sub Cat Six (5)", "Sub Cat Seven (14)", "Sub Cat Eight (24)"];

  subItemContainer = new View({
    properties: {
      y: 1136
    },
    clip: false
  });

  hideSub = function() {
    subItemContainer.animate({
      properties: {
        opacity: 0
      },
      curve: "ease-out",
      time: 300
    });
    return subItemContainer.destroy();
  };

  showSub = function() {
    subItemContainer = new View({
      properties: {
        y: 1136,
        width: 640
      },
      clip: false,
      style: {
        backgroundColor: "#fafafa"
      }
    });
    return subItems.map(function(item, index) {
      var subItemView;
      subItemView = new View({
        superView: subItemContainer,
        width: 640,
        height: 88,
        x: 640,
        y: 304 + index * 88,
        opacity: 0,
        clip: true,
        "class": 'framer list'
      });
      subItemView.style = {
        borderBottom: "1px solid rgba(0,0,0,.2)",
        lineHeight: "" + subItemView.height + "px",
        color: "#75787b",
        paddingLeft: "40px",
        cursor: "pointer",
        backgroundColor: "#fafafa"
      };
      subItemView.html = "" + item;
      utils.delay(index * 30, function() {
        return subItemView.animate({
          properties: {
            x: 0,
            opacity: 1
          },
          curve: "spring(400,30,800)"
        });
      });
      return subItemView.on(Events.TouchStart, function() {
        return alert("Load Sub-Category");
      });
    });
  };

}).call(this);
